def draw_park():
    print("+++++++++++++++++++++++")
    print("*                     *")
    print("*                     *")
    print("*                     *")
    print("*                     *")
    print("*              {}     *")
    print("*            {}       *")
    print("*          {}         *")
    print("*        {}           *")
    print("*        {}           *")
    print("*        {}           *")
    print("*        {}           *")
    print("*                     *")
    print("*                     *")
    print("*                     *")
    print("*                     *")
    print("*                     *")
    print("*                     *")
    print("+++++++++++++++++++++++")
    return
